



InboxSDK.load('1', 'sdk_autoreply_c87f866c58').then(function(sdk){

	// the SDK has been loaded, now do something with it!
	sdk.Compose.registerComposeViewHandler(function(composeView){

		// a compose view has come into existence, do something with it!
		composeView.addButton({
			title: "Generate Draft",
			iconUrl: 'https://lh5.googleusercontent.com/itq66nh65lfCick8cJ-OPuqZ8OUDTIxjCc25dkc4WUT1JG8XG3z6-eboCu63_uDXSqMnLRdlvQ=s128-h128-e365',
			// onClick: generateDraft(event),
			onClick: function(event) {
				generateDraft(event);
			},
		});
		composeView.addButton({
			title: "Classify Email",
			onClick: function(event) {
				event.s
			}
		})

	});

});

function generateDraft(event) {
	email_body = 'Hello , \n\n this is an automated email generated by Autoreply. Thank you for using our services. \n\n -Autobot'
	event.composeView.insertTextIntoBodyAtCursor(email_body);
}


// Asynchronous hpptGet function
// function httpGetAsync(theUrl, callback)
// {
//     var xmlHttp = new XMLHttpRequest();
//     xmlHttp.onreadystatechange = function() { 
//         if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
//             callback(xmlHttp.responseText);
//     }
//     xmlHttp.open("GET", theUrl, true); // true for asynchronous 
//     xmlHttp.send(null);
// }
