var j = document.createElement('script');
j.src = chrome.extension.getURL('jquery-1.10.2.min.js');
(document.head || document.documentElement).appendChild(j);

var g = document.createElement('script');
g.src = chrome.extension.getURL('gmail.js');
(document.head || document.documentElement).appendChild(g);

var s = document.createElement('script');
s.src = chrome.extension.getURL('main.js');
(document.head || document.documentElement).appendChild(s);

/**
* The category names we will be using are as follows:
* 1. miscl. -- Any miscellaneous emails that don't belong to one of the categories above (anything that we can't generate a generic response to)
* 2. conflicts -- Anything related to midterm/final scheduling conflicts
* 3. attendance -- 
* 4. hw -- Anything related to homework (e.g. submissions)
* 5. enrollment -- Anything related to Calcentral/course enrollment issues
* 6. `internal`-- Anything related to course logistics, hiring, or other administrative issues
* 7. dsp 
* 8. regrades
*/

var emailLabelDict = {
	1 : 'Miscellaneous',
	2 : 'Conflicts',
	3 : 'Attendance',
	4 : 'Homework',
	5 : 'Enrollment',
	6 : 'Internal',
	7 : 'DSP',
	8 : 'Regrades'
};

var labelColorDict = {
 	1 : '#e08a85',
 	2 : '#e0cf85',
 	3 : '#ade085',
 	4 : '#85e0a1',
 	5 : '#85dbe0',
 	6 : '#8596e0',
 	7 : '#b885e0',
 	8 : '#e085c4'
}


InboxSDK.load('1', 'sdk_autoreply_c87f866c58').then(function(sdk){

	// the SDK has been loaded, now do something with it!
	sdk.Compose.registerComposeViewHandler(function(composeView){

		// a compose view has come into existence, do something with it!
		composeView.addButton({
			title: "Generate Draft",
			iconUrl: chrome.runtime.getURL('images/compose_64.png'), //<div>Icons made by <a href="https://www.flaticon.com/authors/smashicons" title="Smashicons">Smashicons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
			// onClick: generateDraft(event),
			onClick: function(event) {
				generateDraft(event);
			},
		});
	});

	sdk.Conversations.registerThreadViewHandler(threadView => {
		const el = document.createElement("div");
		el.innerHTML = 'Email Analytics';

		threadView.addSidebarContentPanel({
			title: 'Sidebar Example',
			iconUrl: chrome.runtime.getURL('images/analytics.png'),
			el
		});
	});

	sdk.Lists.registerThreadRowViewHandler(function(threadRowView) {

		var contacts = threadRowView.getContacts();
		for (var i = 0; i < contacts.length; i++) {
			var contact = contacts[i];
			//console.log(contact);
			if (getBerkeleyEmail(contact, sdk.User.getEmailAddress())) {
				addEmailLabelToThreadRow(threadRowView, contact.emailAddress);
      			//addEmailIndicatorToThreadRow(threadRowView, contact.emailAddress);
      		}
		}
	});
});

/**
* Generates and inserts draft into body
* @param event
*/
function generateDraft(event) {
	email_body = 'Hello, \n\n This is an automated email generated by Flo. Thank you for using our services. \n\n -Flo'
	event.composeView.insertTextIntoBodyAtCursor(email_body);
}

/**
* Adds a checkmark icon to email thread
* @param threadRowView
* @param email
*/
function addEmailIndicatorToThreadRow(threadRowView, email) {
	threadRowView.addImage({
		imageUrl: chrome.runtime.getURL('images/checked.png'), //<div>Icons made by <a href="https://www.flaticon.com/authors/maxim-basinski" title="Maxim Basinski">Maxim Basinski</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
		tooltip: email,
    imageClass: 'rounded_check'
	});
}

/**
* Only classify emails that end with @berkeley.edu
* @param contact - contact of current thread
* @param currentUserEmail
*/
function getBerkeleyEmail(contact, currentUserEmail) {
	if (contact.emailAddress.split("@")[1] === currentUserEmail.split("@")[1]) {
		return true;
	} else {
		return true; //false;
	}
}

/**
* Currently randomly generates a number between 1 - 8
*/
function classifyEmail(emailData) {
	return Math.floor(Math.random() * 8) + 1;
}

/**
* Add label icon to each threadRowView
* @param threadRowView : current threadRow in view
* @param emailData : emailData of current thread
*/
function addEmailLabelToThreadRow(threadRowView, emailData) {
	var emailClass = classifyEmail(emailData); //int class of label
	var label = emailLabelDict[emailClass]; // label string
	var labelColor = labelColorDict[emailClass]; // HEX val of label color

	threadRowView.addLabel({
		title: label,
		foregroundColor: '#ffffff',
		backgroundColor: labelColor,
		iconUrl: chrome.runtime.getURL('images/tag_64.png')
	});
}
